site_name: LEPAM Docs
site_url: https://yauhenitalochkan.github.io/LEPAM_Docs/
nav:
  - Home: index.md
  - Installation: install.md
  - Processes: processes.md
  - About: about.md
  - References: references.md

theme:
  name: readthedocs

plugins:
  - glightbox

copyright: |
  &copy; 2024 <a href="https://github.com/YauheniTalochkaN"  target="_blank" rel="noopener">Yauheni Talochka</a>