site_name: LEPAM Docs
site_url: https://yauhenitalochkan.github.io/LEPAM_Docs/
nav:
  - Home: index.md
  - Installation: install.md
  - Processes: processes.md
  - References: references.md

theme:
  name: readthedocs

plugins:
  - glightbox

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

copyright: |
  &copy; 2024 <a href="https://github.com/YauheniTalochkaN"  target="_blank" rel="noopener">Yauheni Talochka</a>